---
- name: Add managed vhost config file (if any vhosts are configured).
  template:
    src: vhosts.j2
    dest: "{{ nginx.vhost_path }}/vhosts.conf"
    mode: 0644
  when: nginx.vhosts
  notify: restart nginx

- name: Remove managed vhost config file (if no vhosts are configured).
  file:
    path: "{{ nginx.vhost_path }}/vhosts.conf"
    state: absent
  when: not nginx.vhosts
  notify: restart nginx
